
import { Inter } from "next/font/google";
import "./globals.scss";
import "bootstrap/dist/css/bootstrap.min.css";
import "../assets/css/style.css";
import Footer from "@/FooterComponents/Footer";
import Navlinks from "@/HomeComponents/Navlinks";
import Dropdownbtn from "@/HomeComponents/Dropdownbtn";
import SocialIcons from "@/HomeComponents/SocialIcons";
import Stores from "@/HomeComponents/Stores";
import Navbar from "@/HomeComponents/Navbar";
// import Navbar from "@/Components/Navbar";
// import Navbar2 from "@/Components/Navbar2";

// Configure Inter font
const inter = Inter({
  subsets: ["latin"],
  display: 'swap', // Optional: improves performance
  variable: '--font-inter', // Optional: for CSS variables
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
       <Navbar></Navbar>
        {/* <Navbar2></Navbar2> */}
        {children}
        {/* <Footer></Footer> */}
      </body>
    </html>
  );
}